"""
Genera PDFs de ejemplo con datos inventados para la carpeta samples/.

Los PDFs tienen la estructura mínima necesaria para que los parsers de renta
funcionen, pero no replica el layout visual de los documentos reales.

Uso:
    python scripts/generate_sample_pdfs.py

Requiere: fpdf2 (pip install -e ".[dev]")
"""

from pathlib import Path

import pdfplumber
from fpdf import FPDF

SAMPLES_DIR = Path(__file__).parent.parent / "samples"

SAMPLE_NOTICE = (
    "SAMPLE FILE - Fake data generated for testing purposes.\n"
    "It has the minimum structure required by the parsers.\n"
    "Real broker PDFs have a much richer layout than this sample.\n"
    "Generated by scripts/generate_sample_pdfs.py"
)


# ---------------------------------------------------------------------------
# Fidelity PDF
# ---------------------------------------------------------------------------

FIDELITY_DIVIDENDS = [
    "Jan-25-2024 Dividend / Interest $47.20 USD",
    "Apr-15-2024 Dividend / Interest $52.30 USD",
    "Jul-15-2024 Dividend / Interest $52.30 USD",
    "Oct-15-2024 Dividend / Interest $48.10 USD",
    "Dec-20-2024 Dividend / Interest $50.10 USD",
]

FIDELITY_SALES = [
    "Mar-12-2024 May-05-2020 10.0000 $500.00 $1,200.00 +$700.00 USD RS",
    "Jun-20-2024 Feb-15-2021 5.0000 $650.00 $800.00 +$150.00 USD RS",
    "Sep-15-2024 Sep-10-2024 8.0000 $1,100.00 $1,050.00 -$50.00 USD RS",
    "Nov-22-2024 Mar-01-2022 12.0000 $780.00 $1,530.00 +$750.00 USD RS",
]

FIDELITY_WITHHOLDINGS = [
    "Jan-25-2024 Other -$7.08 USD",
    "Apr-15-2024 Other -$7.85 USD",
    "Jul-15-2024 Other -$7.85 USD",
    "Jul-31-2024 Other $0.03 USD",
    "Oct-15-2024 Other -$7.22 USD",
    "Dec-20-2024 Other -$7.53 USD",
]

FIDELITY_HEADER = (
    "Fidelity Investments\n"
    "Sample Data - Not a real account\n"
    "MARIA GARCIA LOPEZ\n"
    "Calle Inventada 42, 28001 Madrid, Spain\n"
    "Account: Z99-887766\n"
    + SAMPLE_NOTICE
)

FIDELITY_SUMMARY_DATA = (
    "Dividend income  5 transactions \u00b7 Total $250.00 USD\n"
    "Stock sales  4 transactions \u00b7 Total $1,550.00 USD\n"
    "Nonresident alien withholding  6 transactions \u00b7 Total -$37.50 USD\n"
    "Total amount: $1,762.50 USD"
)


def _fidelity_page(
    pdf: FPDF,
    header: str,
    section_header: str,
    data: str,
    footer: str,
    page_w: float,
) -> None:
    """Añade una página al PDF de Fidelity con 4 celdas apiladas verticalmente."""
    pdf.add_page()
    # Calculamos alturas proporcionales al contenido
    line_h = 5
    margin = pdf.l_margin
    cell_w = page_w - margin * 2

    rows = [header, section_header, data, footer]
    for row_text in rows:
        n_lines = row_text.count("\n") + 1
        h = line_h * n_lines + 4
        pdf.multi_cell(cell_w, line_h, row_text, border=1)
        pdf.ln(0)


def generate_fidelity(output_path: Path) -> None:
    pdf = FPDF(orientation="P", unit="mm", format="A4")
    pdf.set_margins(10, 10, 10)
    pdf.set_auto_page_break(auto=False)
    pdf.set_font("Helvetica", size=8)
    page_w = 210.0  # A4 width mm

    # Página 1: resumen
    _fidelity_page(
        pdf,
        FIDELITY_HEADER,
        "Custom Transaction Summary\nJan-01-2024 to Dec-31-2024",
        FIDELITY_SUMMARY_DATA,
        "Page 1 of 4",
        page_w,
    )

    # Página 2: dividendos
    _fidelity_page(
        pdf,
        FIDELITY_HEADER,
        "Dividend income\nTransaction date  Transaction type  Amount",
        "\n".join(FIDELITY_DIVIDENDS),
        "Page 2 of 4",
        page_w,
    )

    # Página 3: ventas
    _fidelity_page(
        pdf,
        FIDELITY_HEADER,
        "Stock sales\nORCL: ORACLE CORP\nDate sold  Date acquired  Quantity  Cost basis  Proceeds  Gain/loss  Stock source*",
        "\n".join(FIDELITY_SALES),
        "Page 3 of 4\n*SP=ESPP RS=RSU/PSU/RSA SA=SAR NQ=Non-qual options ISO=Qual options DO=Deposit only",
        page_w,
    )

    # Página 4: retenciones
    _fidelity_page(
        pdf,
        FIDELITY_HEADER,
        "Nonresident alien withholding\nTransaction date  Transaction type  Amount",
        "\n".join(FIDELITY_WITHHOLDINGS),
        "Page 4 of 4",
        page_w,
    )

    pdf.output(str(output_path))
    print(f"  Fidelity PDF escrito: {output_path}")


# ---------------------------------------------------------------------------
# Koinly PDF
# ---------------------------------------------------------------------------

KOINLY_GAINS = [
    "29/07/2024 14:35 17/01/2018 23:10 BTC 0.00152000 15.55 97.82 82.27 Kraken",
    "15/10/2024 09:20 03/05/2021 11:30 ETH 0.50000000 120.00 195.50 75.50 Coinbase",
]

KOINLY_REWARDS = [
    "01/01/2024 01:00 ADA 0.50000000 0.25 Reward Flexible REALTIME Binance",
    "15/01/2024 13:00 STETH 0.00100000 2.50 Reward stETH Binance",
    "01/02/2024 01:00 ADA 0.48000000 0.24 Reward Flexible REALTIME Binance",
    "15/02/2024 13:00 DOT 0.10000000 0.80 Reward Staking Kraken",
    "01/03/2024 01:00 ADA 0.52000000 0.26 Reward Flexible REALTIME Binance",
    "15/04/2024 08:00 ETH 0.00050000 1.55 Reward stETH Lido",
    "01/06/2024 01:00 ADA 0.49000000 0.30 Reward Flexible REALTIME Binance",
    "15/07/2024 13:00 STETH 0.00080000 2.40 Reward stETH Binance",
    "01/09/2024 01:00 ADA 0.51000000 0.27 Reward Flexible REALTIME Binance",
    "15/11/2024 13:00 DOT 0.12000000 0.93 Reward Staking Kraken",
]


def _koinly_text_page(pdf: FPDF, lines: list[str]) -> None:
    """Añade una página de texto plano al PDF de Koinly."""
    pdf.add_page()
    line_h = 5
    for line in lines:
        from fpdf.enums import XPos, YPos
        pdf.cell(0, line_h, line, new_x=XPos.LMARGIN, new_y=YPos.NEXT)


def generate_koinly(output_path: Path) -> None:
    pdf = FPDF(orientation="P", unit="mm", format="A4")
    pdf.set_margins(10, 10, 10)
    pdf.set_auto_page_break(auto=False)
    pdf.set_font("Helvetica", size=8)

    # Página 1: portada
    _koinly_text_page(pdf, [
        "Koinly - Complete Tax Report",
        "1 ene 2024 hasta 31 dic 2024",
        "Metodo contable: FIFO",
        "Moneda base: EUR",
        "Generado: 01/04/2025",
        "",
        SAMPLE_NOTICE,
        "",
        "Tabla de contenidos:",
        "  1. Resumen de ganancias patrimoniales",
        "  2. Resumen de rendimientos",
        "  3. Operaciones de Ganancias Patrimoniales",
        "  4. Operaciones de rendimientos",
    ])

    # Página 2: resumen de ganancias patrimoniales
    _koinly_text_page(pdf, [
        "Resumen de ganancias patrimoniales",
        "",
        "Numero de ventas: 2",
        "Ingresos por ventas: EUR 293.32",
        "Costes de adquisicion: EUR 135.55",
        "Ganancias: EUR 157.77",
        "Perdidas: EUR 0.00",
        "Ganancias netas 157.77",
    ])

    # Página 3: resumen de rendimientos
    _koinly_text_page(pdf, [
        "Resumen de rendimientos",
        "",
        "Reward: EUR 9.50",
        "Total EUR9.50",
        "",
        "Informe de gastos",
        "Total EUR0.00",
    ])

    # Página 4: ganancias patrimoniales
    _koinly_text_page(pdf, [
        "Operaciones de Ganancias Patrimoniales",
        "",
        "Fecha de Venta  Fecha de Adquisicion  Activo  Cantidad  Valor (EUR)  Ingresos (EUR)  Ganancias/Perdidas  Wallet",
    ] + KOINLY_GAINS)

    # Página 5: rendimientos/rewards
    _koinly_text_page(pdf, [
        "Operaciones de rendimientos",
        "",
        "Fecha  Activo  Cantidad  Precio (EUR)  Tipo  Descripcion  Wallet",
    ] + KOINLY_REWARDS)

    pdf.output(str(output_path))
    print(f"  Koinly PDF escrito: {output_path}")


# ---------------------------------------------------------------------------
# DEGIRO PDF
# ---------------------------------------------------------------------------

DEGIRO_HEADER = (
    "flatexDEGIRO Bank AG\n"
    "Informe Fiscal para el año 2024\n"
    "MARIA GARCIA LOPEZ\n"
    "NIF: 12345678Z\n"
    + SAMPLE_NOTICE
)

DEGIRO_SUMMARY = (
    "Resumen\n"
    "\n"
    "Ganancias / Pérdidas Realizadas\n"
    "Ganancias patrimoniales totales: 1,9045 EUR\n"
    "Pérdidas totales: 5,2300 EUR\n"
)

DEGIRO_DIVIDENDS = (
    "Dividendos, Cupones y otras remuneraciones\n"
    "\n"
    "País Producto Ingreso bruto Retenciones a cuenta Ingreso neto\n"
    "NL PROSUS NV 1,50 EUR -0,23 EUR 1,28 EUR\n"
    "1,50 EUR -0,23 EUR 1,28 EUR\n"
    "US ARES CAPITAL CORP 2,56 EUR -0,38 EUR 2,18 EUR\n"
    "4,06 EUR -0,59 EUR 3,48 EUR\n"
)

DEGIRO_SALES = (
    "Relación de ganancias y pérdidas por producto\n"
    "\n"
    "Producto Symbol/ISIN Ganancias/Pérdidas brutas realizadas Comisión pagada Impuesto\n"
    "Total 0,00 EUR 0,00 EUR 0,00 EUR\n"
)


def generate_degiro(output_path: Path) -> None:
    pdf = FPDF(orientation="P", unit="mm", format="A4")
    pdf.set_margins(10, 10, 10)
    pdf.set_auto_page_break(auto=False)
    pdf.set_font("Helvetica", size=8)

    # Página 1: cabecera
    _koinly_text_page(pdf, DEGIRO_HEADER.splitlines())

    # Página 2: resumen ganancias/pérdidas
    _koinly_text_page(pdf, DEGIRO_SUMMARY.splitlines())

    # Página 3: dividendos
    _koinly_text_page(pdf, DEGIRO_DIVIDENDS.splitlines())

    # Página 4: ventas detalladas
    _koinly_text_page(pdf, DEGIRO_SALES.splitlines())

    pdf.output(str(output_path))
    print(f"  DEGIRO PDF escrito: {output_path}")


# ---------------------------------------------------------------------------
# Verificación post-generación
# ---------------------------------------------------------------------------

def verify_fidelity(pdf_path: Path) -> bool:
    ok = True
    with pdfplumber.open(pdf_path) as pdf:
        for i, page in enumerate(pdf.pages, 1):
            tables = page.extract_tables()
            if not tables or len(tables[0]) < 3:
                print(f"  [WARN] Fidelity pag {i}: tabla no detectada o <3 filas ({len(tables[0]) if tables else 0} filas)")
                ok = False
            else:
                print(f"  [OK]   Fidelity pag {i}: tabla con {len(tables[0])} filas detectada")
    return ok


def verify_degiro(pdf_path: Path) -> bool:
    ok = True
    required = [
        "flatexDEGIRO",
        "Informe Fiscal para el año 2024",
        "Dividendos, Cupones y otras remuneraciones",
        "PROSUS NV",
        "4,06 EUR",
        "Relación de ganancias y pérdidas por producto",
    ]
    full_text = ""
    with pdfplumber.open(pdf_path) as pdf:
        for page in pdf.pages:
            full_text += page.extract_text() or ""

    for marker in required:
        if marker in full_text:
            print(f"  [OK]   DEGIRO: encontrado '{marker}'")
        else:
            print(f"  [WARN] DEGIRO: NO encontrado '{marker}'")
            ok = False
    return ok


def verify_koinly(pdf_path: Path) -> bool:
    ok = True
    required = [
        "Koinly",
        "Ganancias netas 157.77",
        "Resumen de rendimientos",
        "Total EUR9.50",
        "Operaciones de Ganancias Patrimoniales",
        "Operaciones de rendimientos",
    ]
    full_text = ""
    with pdfplumber.open(pdf_path) as pdf:
        for page in pdf.pages:
            full_text += page.extract_text() or ""

    for marker in required:
        if marker in full_text:
            print(f"  [OK]   Koinly: encontrado '{marker}'")
        else:
            print(f"  [WARN] Koinly: NO encontrado '{marker}'")
            ok = False
    return ok


# ---------------------------------------------------------------------------
# Main
# ---------------------------------------------------------------------------

def main() -> None:
    SAMPLES_DIR.mkdir(exist_ok=True)

    fidelity_path = SAMPLES_DIR / "Fidelity 2024 summary.pdf"
    koinly_path = SAMPLES_DIR / "Koinly 2024 complete tax report.pdf"
    degiro_path = SAMPLES_DIR / "DEGIRO 2024 informe fiscal.pdf"

    print("Generando PDFs de ejemplo...")
    generate_fidelity(fidelity_path)
    generate_koinly(koinly_path)
    generate_degiro(degiro_path)

    print("\nVerificando estructura con pdfplumber...")
    fidelity_ok = verify_fidelity(fidelity_path)
    koinly_ok = verify_koinly(koinly_path)
    degiro_ok = verify_degiro(degiro_path)

    if fidelity_ok and koinly_ok and degiro_ok:
        print("\nOK: Todos los PDFs generados y verificados correctamente.")
        print(f"Prueba con: .venv/bin/python -m renta calcular --input {SAMPLES_DIR}/")
    else:
        print("\nATENCION: Algunos checks fallaron. Revisa los warnings arriba.")


if __name__ == "__main__":
    main()
